name: Docker Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "kstawiski/jobczyk2020-app"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
